.PHONY: clean All

All:
	@echo "----------Building project:[ shopping - Debug ]----------"
	@cd "shopping" && "$(MAKE)" -f  "shopping.mk"
clean:
	@echo "----------Cleaning project:[ shopping - Debug ]----------"
	@cd "shopping" && "$(MAKE)" -f  "shopping.mk" clean
