.PHONY: clean All

All:
	@echo "----------Building project:[ SBG-Hobbit - Debug ]----------"
	@cd "SBG-Hobbit" && "$(MAKE)" -f  "SBG-Hobbit.mk"
clean:
	@echo "----------Cleaning project:[ SBG-Hobbit - Debug ]----------"
	@cd "SBG-Hobbit" && "$(MAKE)" -f  "SBG-Hobbit.mk" clean
